### PR TITLE
Day 4 task: Basic GIT commands

### PR DESCRIPTION
**Pull request by imran99744**
Let's get prepared for day 4 of learning.

### CODE REVIEW

**Review by shubhamlondhe1996 — CHANGES_REQUESTED** [review]
We can keep git  in second week..
lets make Linux fundamentals stronger till day 7..
try adding shell scripting

**Comment by imran99744** [comment]
@shubhamlondhe1996 okay, understand. Definitely, I will add Linux fundamentals and shell/bash scripting.

**Review by LondheShubham153 — CHANGES_REQUESTED** [review]
Thanks @imran99744 
this is good but you have to give tasks, questions too, in an easy way.
I will write tasks for Day 4, can you and @shakhscode take day 5?

**Comment by imran99744** [comment]
okay, Thanks for your guideline/comment. I will add tasks according to your instruction.

**Pull request closed without merging**
