### PR TITLE
Create Linux-Architecture-WithCommands.md

### PR DESCRIPTION
**Pull request by singhmohit14072002**

### CODE REVIEW

**Comment by singhmohit14072002** [comment]
- Heyy, Shubhum can you review my pr .

**Review by jayvardhan2111 — APPROVED** [review]

**Review by singhmohit14072002 — COMMENTED** [review]
- should I change anything or its ok to be merged

**Comment by jayvardhan2111** [comment]
> 

I think you should wait for subham bhaiya reply

**Comment by jayvardhan2111** [comment]
> * should I change anything or its ok to be merged

Ok, you can merge

**Comment by singhmohit14072002** [comment]
> > * should I change anything or its ok to be merged
> 
> Ok, you can merge

> 

>Ok

**Review by jayvardhan2111 — APPROVED** [review]

**Review by jayvardhan2111 — APPROVED** [review]

**Pull request closed without merging**
