### PR TITLE
Day 5 task: Shell scripting application.

### PR DESCRIPTION
**Pull request by shakhscode**
Added a simple task to write a shell script that creates directories with dynamic name.

### CODE REVIEW

**Review by LondheShubham153 — COMMENTED** [review]
This looks amazing, but @shakhscode can we keep this as Day 5?
And give a simpler shell scripting task for day 4?
I'll add day 4 and we can make this as day 5

**Comment by shakhscode** [comment]
Sure sir! Good idea.

**Comment by shakhscode** [comment]
Updated the task for day 5

**Review by LondheShubham153 — APPROVED** [review]
LGTM, 
thanks
@shakhscode I will be modifying it further to add permissions

**Pull request merged**
