### PR TITLE
Solution day 10 by mohit

### PR DESCRIPTION
**Pull request by Mohit76655**

### CODE REVIEW

**Comment by Bhavin213** [comment]
Hi Mohit,

The pull request you created isn't done correctly. Please refer to the document or video ([Git and GitHub Master Class By Shubham Londhe](https://youtu.be/AT1uxOLsCdk?si=neWo_H-Cbr0wJTBH)) on how to properly make a pull request. Additionally, check the Day 8/9 solution.md file to get an idea of the correct process. Make sure to create a proper solution.md file.

Thank you.

**Comment by Mohit76655** [comment]
@Bhavin213 hey , can you point out the mistake , i don't know where it goes wrong

**Comment by Mohit76655** [comment]
@LondheShubham153 

hello sir, 
can you please tell me where my pull request goes wrong (can you point out the mistake)

Thank you.

**Comment by Bhavin213** [comment]
- What I mean to say is that you should include the code along with its output. For reference, I have created many solution.md file. Please make yours in a similar format.
- Don't worry. In yesterday's doubt session, sir mentioned that he will teach GitHub-related topics in the Saturday class.

**Comment by Mohit76655** [comment]
@Bhavin213 that's exactly what I did , first check/read the whole solution.md & i know git i'm using git for more than 2 years ( i have more than 30 project's & 300+ commit's on github so i can say that i know git github

**Comment by Bhavin213** [comment]
I appreciate your experience with Git and GitHub.

**Pull request closed without merging**
