### PR TITLE
cheat sheet for Linux and Git

### PR DESCRIPTION
**Pull request by rajatchauhan-git**
Creating a pull request to upload a cheat sheet for Linux and Git on Day-14

### CODE REVIEW

**Review by RishOpss — APPROVED** [review]

**Review by rajatchauhan-git — COMMENTED** [review]
@shubhamlondhe1996 : Any changes required?

**Comment by rajatchauhan-git** [comment]
@shubhamlondhe1996 @Bhavin213  Please review and accept

**Comment by Bhavin213** [comment]
I checked the cheat sheet; it's properly made. Well done!

**Comment by Bhavin213** [comment]
> @rajatchauhan-git 

I checked the cheat sheet; it's properly made. Well done!

**Pull request merged**
